### ISSUE TITLE
Image can't be rendered

### ISSUE THREAD

**Issue by tembokk** [nvim-telescope/telescope-media-files.nvim#10]
I'm sorry this is probably just a dumb issue but this plugin seems can't work on my machine. I've installed ueberzug tho.
![Screenshot from 2021-06-20 17-39-13](https://user-images.githubusercontent.com/85908574/122670893-75943180-d1ee-11eb-8fae-8017749f7863.png)

**Comment by elianiva** [comment]
are you on wayland?

**Comment by tembokk** [comment]
Ah sorry for the late reply. Yes I'm on wayland. So does ueberzug only run on X?

**Comment by elianiva** [comment]
correct, ueberzug doesn't work on Wayland, only on Xorg
