### ISSUE TITLE
Images with `-` in the filename don't render appear to render.

### ISSUE THREAD

**Issue by ChristianChiarulli** [nvim-telescope/telescope-media-files.nvim#4]
I almost thought it didn't work. I uninstalled it like a week ago and re-installed today to see if it would work, then I noticed all of the ones without hyphens worked fine.

**Comment by elianiva** [comment]
wait what, my last commit was supposed to fix this. (and it did, at least for me and the other guy)
let me double check what's going on

**Comment by ChristianChiarulli** [comment]
Maybe I didn’t update. I’ll check again.
