### ISSUE TITLE
Error when launching `Telescope media_files`

### ISSUE THREAD

**Issue by brymer-meneses** [nvim-telescope/telescope-media-files.nvim#7]
![Screenshot from 2021-05-07 10-27-47](https://user-images.githubusercontent.com/68867487/117389427-ef15e000-af1e-11eb-9fe4-ea5f5fb2dc47.png)
I get the following error when I execute `Telescope media_files`

**Comment by windwp** [comment]
are you install ueberzeg.
check readme and install depend tool

**Comment by brymer-meneses** [comment]
Hello @windwp, I have installed ueberzeg. In fact I can preview images just fine using ranger.

**Comment by brymer-meneses** [comment]
I fixed this by making sure that `require('telescope').load_extension('media_files')` is written below `require('telescope').setup{...}`

I previously had
```lua
require('telescope').load_extension('media_files')
require('telescope').setup {
    extensions = {
        media_files = {
            filetypes = {"png", "jpg", "pdf", "jpeg"},
            find_cmd = "rg"
        }
    }
}

```

Now I have
```lua

require('telescope').setup {
    extensions = {
        media_files = {
            filetypes = {"png", "jpg", "pdf", "jpeg"},
            find_cmd = "rg"
        }
    }
}
require('telescope').load_extension('media_files')

```
